name: YangBaxter
version: 0.10.2
date: 2022-12-12
description: |
    Combinatorial Solutions for the Yang-Baxter equation

authors:
    - name: Leandro Vendramin
      url: https://vendramin.github.io/
    - name: Olexandr Konovalov
      url: https://alex-konovalov.github.io/

maintainers:
    - name: Leandro Vendramin
      url: https://vendramin.github.io/
    - name: Olexandr Konovalov
      url: https://alex-konovalov.github.io/

GAP: ">=4.9"

needed-pkgs:
    - name: "cryst"
      version: ">=4.0"
      url: "https://www.math.uni-bielefeld.de/~gaehler/gap/packages.php"

www: https://gap-packages.github.io/YangBaxter
readme: README.md
packageinfo: https://gap-packages.github.io/YangBaxter/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/YangBaxter/releases/download/v0.10.2/YangBaxter-0.10.2.tar.gz

abstract: |
    The <span class="pkgname">YangBaxter</span> package provides functionality to construct classical and skew braces. It also includes a database of classical and skew braces of small orders.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
