name: YangBaxter
version: "0.10.5"
license: "GPL-3.0"
date: 2024-06-15
description: |
    Combinatorial Solutions for the Yang-Baxter equation

authors:
    - name: Leandro Vendramin
      url: https://vendramin.github.io/
    - name: Olexandr Konovalov
      url: https://olexandr-konovalov.github.io/

maintainers:
    - name: Leandro Vendramin
      url: https://vendramin.github.io/
    - name: Olexandr Konovalov
      url: https://olexandr-konovalov.github.io/

GAP: ">=4.9"

needed-pkgs:
    - name: "cryst"
      version: ">=4.0"
      url: "https://www.math.uni-bielefeld.de/~gaehler/gap/packages.php"

www: https://gap-packages.github.io/YangBaxter
readme: README.md
packageinfo: https://gap-packages.github.io/YangBaxter/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/YangBaxter/releases/download/v0.10.5/YangBaxter-0.10.5.tar.gz

abstract: |
    The <span class="pkgname">YangBaxter</span> package provides functionality to construct classical and skew braces. It also includes a database of classical and skew braces of small orders.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    QYBE, cycle sets, racks, quandles, braces, radical rings.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>VK24</span>]   <b class='BibAuthor'>Vendramin, L. and Konovalov, O.</b>,
     <i class='BibTitle'>YangBaxter, Combinatorial Solutions for the Yang-Baxter equation,
             Version 0.10.5</i>
     (<span class='BibYear'>2024</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/YangBaxter">https://gap-packages.github.io/YangBaxter</a></span>.
    </p>
    

bibtex: |
    @misc{ YangBaxter,
      author =           {Vendramin, L. and Konovalov, O.},
      title =            {{YangBaxter},    Combinatorial   Solutions   for   the
                          Yang\texttt{\symbol{45}}Baxter   equation,   {V}ersion
                          0.10.5},
      month =            {Jun},
      year =             {2024},
      note =             {GAP package},
      howpublished =     {\href      {https://gap-packages.github.io/YangBaxter}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{YangBaxter}}},
      keywords =         {QYBE;  cycle  sets;  racks;  quandles; braces; radical
                          rings},
      printedkey =       {VK24}
    }

