# YangBaxter, chapter 1
#
# DO NOT EDIT THIS FILE - EDIT EXAMPLES IN THE SOURCE INSTEAD!
#
# This file has been autogenerated with GAP. It contains examples
# extracted from the documentation. Each example is preceded by the
# comment which points to the location of its source.
#
gap> START_TEST( "yangbaxter01.tst");

# YangBaxter/doc/../lib/skew.gd:24-29

gap> SmallSkewBrace(8,3);
<brace of size 8>

gap> STOP_TEST("yangbaxter01.tst", 1 );
